# Imported the Libraries

In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Imported the Datasets

In [6]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

In [7]:
df_train

field_id  soil_ph  organic_matter  sand_pct  temperature  humidity  \
0      F00001     6.25            2.66      41.6         25.2        70   
1      F00002     6.70            3.66      40.2         26.9        78   
2      F00003     7.21            3.45      40.0         27.6        66   
3      F00004     5.73            2.48      56.9         29.6        79   
4      F00005     6.88            3.61      30.6         25.0        80   
...       ...      ...             ...       ...          ...       ...   
9995   F09996     6.23            1.76      34.0         29.2        65   
9996   F09997     7.05            2.80      32.8         27.4        76   
9997   F09998     7.00            3.97      55.3         26.9        67   
9998   F09999     7.30            1.59      54.1         28.4        84   
9999   F10000     6.11            2.65      50.1         26.1        76   

      rainfall  ndvi   yield  
0        110.2  0.46  4105.8  
1        126.3  0.59  4247.8  
2        109.4  0.64  4021.8  
3        155.3  0.62  4326.8  
4        172.6  0.62  3708.0  
...        ...   ...     ...  
9995     156.1  0.69  4747.0  
9996     155.9  0.52  4047.6  
9997     134.0  0.49  4542.2  
9998     118.7  0.70  4191.7  
9999     167.3  0.64  4892.5  

[10000 rows x 9 columns]

In [8]:
df_test

field_id  soil_ph  organic_matter  sand_pct  temperature  humidity  \
0      T00001     6.25            2.15      47.2         27.9        82   
1      T00002     7.40            2.12      54.2         25.0        74   
2      T00003     6.96            3.77      52.8         29.2        75   
3      T00004     6.70            2.12      34.6         27.7        81   
4      T00005     5.81            2.18      34.5         24.9        84   
...       ...      ...             ...       ...          ...       ...   
1995   T01996     6.81            2.61      50.5         25.6        78   
1996   T01997     7.41            2.34      45.1         25.3        80   
1997   T01998     5.64            2.49      53.0         26.7        81   
1998   T01999     5.61            2.82      44.6         29.5        68   
1999   T02000     6.06            1.90      34.5         24.6        77   

      rainfall  ndvi  
0        176.5  0.60  
1        167.5  0.50  
2        155.1  0.43  
3        123.6  0.45  
4        173.1  0.64  
...        ...   ...  
1995     145.8  0.68  
1996     136.7  0.64  
1997     122.2  0.61  
1998     137.1  0.42  
1999     136.0  0.71  

[2000 rows x 8 columns]

In [9]:
X_train = df_train.drop(['field_id', 'yield'], axis = 1).values
y_train = df_train['yield'].values
X_test = df_test.drop(['field_id'],axis = 1).values

In [10]:
X_train

array([[  6.25,   2.66,  41.6 , ...,  70.  , 110.2 ,   0.46],
       [  6.7 ,   3.66,  40.2 , ...,  78.  , 126.3 ,   0.59],
       [  7.21,   3.45,  40.  , ...,  66.  , 109.4 ,   0.64],
       ...,
       [  7.  ,   3.97,  55.3 , ...,  67.  , 134.  ,   0.49],
       [  7.3 ,   1.59,  54.1 , ...,  84.  , 118.7 ,   0.7 ],
       [  6.11,   2.65,  50.1 , ...,  76.  , 167.3 ,   0.64]],
      shape=(10000, 7))

In [11]:
X_test

array([[  6.25,   2.15,  47.2 , ...,  82.  , 176.5 ,   0.6 ],
       [  7.4 ,   2.12,  54.2 , ...,  74.  , 167.5 ,   0.5 ],
       [  6.96,   3.77,  52.8 , ...,  75.  , 155.1 ,   0.43],
       ...,
       [  5.64,   2.49,  53.  , ...,  81.  , 122.2 ,   0.61],
       [  5.61,   2.82,  44.6 , ...,  68.  , 137.1 ,   0.42],
       [  6.06,   1.9 ,  34.5 , ...,  77.  , 136.  ,   0.71]],
      shape=(2000, 7))

In [12]:
y_train

array([4105.8, 4247.8, 4021.8, ..., 4542.2, 4191.7, 4892.5],
      shape=(10000,))

In [ ]:
sns.pairplot(df_train, hue = 'yield')

In [ ]:
sns.heatmap(df_train.drop('field_id', axis = 1).corr(), annot = True)

# Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_val, Y_train, y_val = train_test_split(X_train,y_train, test_size = 0.2, random_state = 0)

# Trainning the Multiple Linear Regression Model on the Training Set

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

# Predicting the Test set results

In [ ]:
y_pred = regressor.predict(x_val)
np.concatenate((y_pred.reshape(len(y_pred),1), y_val.reshape(len(y_val),1)),1)

In [ ]:
y_pred = regressor.predict(X_test)
np.concatenate((y_pred.reshape(len(y_pred),1), y_val.reshape(len(y_val),1)),1)

In [ ]:
y_pred

In [ ]:
from sklearn.metrics import mean_squared_error
y_rmse = np.sqrt(mean_squared_error(y_val, y_pred))

In [ ]:
y_rmse

In [ ]:
regressor.predict([[6.25,2.15,47.2,27.9,82,176.5,0.6]])

In [ ]:
regressor.coef_


In [ ]:
regressor.intercept_

In [ ]:
# Build submission DataFrame
submission = pd.DataFrame({
    "field_id": df_test["field_id"],         
    "yield": y_pred           
})

# Save to CSV
submission.to_csv("sample_submission.csv", index=False)